CREATE TABLE `credentials` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`server` VARCHAR(50) NULL DEFAULT NULL,
	`user` VARCHAR(50) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	`database` VARCHAR(50) NULL DEFAULT NULL,
	`cdt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`times_used` INT(11) NOT NULL DEFAULT '0',
	`last_use` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
;
